import sqlite3
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4

# Create PDF
pdf = canvas.Canvas("carebot_report.pdf", pagesize=A4)
page_width, page_height = A4

# Connect to SQLite database
conn = sqlite3.connect('carebot.db')
cursor = conn.cursor()

# Fetch user and health data (join)
user_id = 1  # Example user id
cursor.execute("""
    SELECT 
        u.name, u.age, u.gender, 
        h.problem, h.summary, h.reported_on, h.created_on
    FROM 
        users u
    INNER JOIN 
        health_records h 
    ON 
        u.id = h.user_id
    WHERE 
        u.id = ?
    ORDER BY h.created_on DESC
""", (user_id,))

records = cursor.fetchall()

if not records:
    print("No records found for this user.")
    exit()

# Use first entry for user info
name, age, gender, *_ = records[0]

# PDF Header: Application name
pdf.setFont("Helvetica-Bold", 20)
pdf.drawCentredString(page_width / 2, page_height - 40, "Care Bot Health Summary")

# Patient Info
pdf.setFont("Helvetica", 12)
pdf.drawString(40, page_height - 90, f"Name: {name}")
pdf.drawString(40, page_height - 110, f"Age: {age}")
pdf.drawString(40, page_height - 130, f"Gender: {gender}")

y_pos = page_height - 170
pdf.setFont("Helvetica-Bold", 14)
pdf.drawString(40, y_pos, "Health Records:")

# Draw each health record section
for record in records:
    _, _, _, problem, summary, reported_on, created_on = record
    y_pos -= 40
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(40, y_pos, f"Problem: {problem}")
    pdf.setFont("Helvetica", 10)
    y_pos -= 15
    pdf.drawString(40, y_pos, f"Reported On: {reported_on}")
    pdf.drawRightString(page_width - 40, y_pos, f"Recorded On: {created_on}")

    y_pos -= 15
    pdf.line(40, y_pos, page_width - 40, y_pos)

    y_pos -= 20
    pdf.setFont("Helvetica", 10)
    pdf.drawString(40, y_pos, f"Summary: {summary}")

    y_pos -= 30

    # Add new page if content overflows
    if y_pos < 100:
        pdf.showPage()
        pdf.setFont("Helvetica", 10)
        y_pos = page_height - 100

# Footer
pdf.setFont("Helvetica-Oblique", 8)
pdf.drawRightString(page_width - 40, 30, "Generated by Care Bot © 2025")

pdf.save()
conn.close()

print("PDF successfully generated -> carebot_report.pdf")
