# pdf_utils.py
import sqlite3
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph
from reportlab.lib.units import inch

def generate_user_pdf(user_id, output_filename="carebot_report.pdf"):
    """Generate PDF for a specific user with all their health records"""
    
    pdf = canvas.Canvas(output_filename, pagesize=A4)
    page_width, page_height = A4

    # Connect to SQLite database
    conn = sqlite3.connect('carebot.db')
    cursor = conn.cursor()

    # Fetch user and health data (join)
    cursor.execute("""
        SELECT 
            u.name, u.age, u.gender, 
            h.problem, h.summary, h.reported_on, h.created_on
        FROM 
            users u
        INNER JOIN 
            health_records h 
        ON 
            u.id = h.user_id
        WHERE 
            u.id = ?
        ORDER BY h.created_on DESC
    """, (user_id,))

    records = cursor.fetchall()

    if not records:
        print("No records found for this user.")
        conn.close()
        return False

    # Use first entry for user info
    name, age, gender, *_ = records[0]

    # PDF Header: Application name
    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawCentredString(page_width / 2, page_height - 40, "Care Bot Health Summary")

    # Patient Info
    pdf.setFont("Helvetica", 12)
    pdf.drawString(40, page_height - 90, f"Name: {name}")
    pdf.drawString(40, page_height - 110, f"Age: {age}")
    pdf.drawString(40, page_height - 130, f"Gender: {gender}")

    y_pos = page_height - 170
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(40, y_pos, "Health Records:")

    # Get styles for Paragraph
    styles = getSampleStyleSheet()
    normal_style = styles['Normal']
    normal_style.fontSize = 10
    normal_style.leading = 14  # line spacing

    # Draw each health record section
    for record in records:
        _, _, _, problem, summary, reported_on, created_on = record
        
        # Check if we need a new page
        if y_pos < 150:
            pdf.showPage()
            pdf.setFont("Helvetica", 10)
            y_pos = page_height - 80
        
        y_pos -= 40
        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(40, y_pos, f"Problem: {problem}")
        pdf.setFont("Helvetica", 10)
        y_pos -= 15
        pdf.drawString(40, y_pos, f"Reported On: {reported_on}")
        pdf.drawRightString(page_width - 40, y_pos, f"Recorded On: {str(created_on)[:19]}")

        y_pos -= 15
        pdf.line(40, y_pos, page_width - 40, y_pos)

        y_pos -= 25
        pdf.setFont("Helvetica-Bold", 10)
        pdf.drawString(40, y_pos, "Summary:")
        
        y_pos -= 15
        
        # Use Paragraph for multi-line text wrapping
        summary_para = Paragraph(f"<para>{summary}</para>", normal_style)
        
        # Calculate the height needed for this paragraph
        available_width = page_width - 80  # 40px margin on each side
        para_width, para_height = summary_para.wrap(available_width, page_height)
        
        # Check if paragraph fits on current page
        if y_pos - para_height < 100:
            pdf.showPage()
            y_pos = page_height - 80
            para_width, para_height = summary_para.wrap(available_width, page_height)
        
        # Draw the paragraph
        summary_para.drawOn(pdf, 40, y_pos - para_height)
        
        # Update y position
        y_pos -= (para_height + 30)

    # Footer
    pdf.setFont("Helvetica-Oblique", 8)
    pdf.drawRightString(page_width - 40, 30, "Generated by Care Bot © 2025")

    pdf.save()
    conn.close()
    
    print(f"PDF successfully generated -> {output_filename}")
    return True
